services:
  recipe_management_system:
    image: joaopdrgoncalves/recipe_management_system:latest
    ports:
      - "8080:8081"
    depends_on:
      - recipes_db
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://recipes_db:5432/recipes_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: true


  recipes_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: recipes_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
