services:
  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    restart: unless-stopped
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins

  jenkins:
    build:
      context: .
      dockerfile: JenkinsDockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins

  recipe_management_system_build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    image: recipe_management_system_test
    working_dir: $PWD
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      TESTCONTAINERS_RYUK_DISABLED: true
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock

  recipe_management_system_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    image: recipe_management_system_test
    entrypoint: ["./gradlew", "test"]
    working_dir: $PWD
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins: